version: 2.1
executors:
  ci-executor:
    docker:
      - image: circleci/node:10.17.0
jobs:
  install-dependencies:
    executor: ci-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v2-{{checksum "yarn.lock" }}
            - dependencies-v2
      - run: yarn install && yarn lerna bootstrap
      - save_cache:
          key: dependencies-v2-{{checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: node_modules
  lint-code:
    executor: ci-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint:code
  lint-commits:
    executor: ci-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint:commits
  test-frontend:
    executor: ci-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn test:frontend
workflows:
  version: 2
  build:
    jobs:
      - install-dependencies
      - lint-commits:
          requires:
            - install-dependencies
      - lint-code:
          requires:
            - install-dependencies
      - test-frontend:
          requires:
            - install-dependencies
