version: 2.1
executors:
  ci-executor:
    docker:
      - image: circleci/node:10.16.3
jobs:
  install-dependencies:
    executor: ci-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-v1-{{checksum "yarn.lock" }}
            - dependencies-v1
      - run: yarn install
      - save_cache:
          key: dependencies-v1-{{checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: node_modules
  lint:
    executor: ci-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint
  test:
    executor: ci-executor
    steps:
      - checkout
      - attach_workspace:
            at: .
      - run: yarn test
  deploy:
    executor: ci-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerpints:
            - "3a:a2:25:c4:65:34:db:a5:f6:45:14:b4:23:78:5b:38"
      - run:
          name: Deploy dev instance
          command: |
            git config user.email "$DEPLOY_COMMIT_EMAIL"
            git config user.name "$DEPLOY_COMMIT_USERNAME"
            yarn deploy
workflows:
  version: 2
  lint_test_deploy:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - test:
          requires:
            - install-dependencies
      - deploy:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
