# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: orders-manager-main-service

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    DB_CONNECT_URL: ${ssm:DB_CONNECT_URL}

functions:
  index:
    handler: src/dev_handlers.index
    events:
      - http:
          path: /
          method: any
          cors:
            origin: '*'
            allowCredentials: true
  test-database:
    handler: src/dev_handlers.testDatabase
    events:
      - http:
          path: /test-db
          method: any
          cors:
            origin: '*'
            allowCredentials: true
  create-order:
    handler: src/create-order_handler.handler
    events:
      - http:
          path: create-order
          method: post
          cors:
            origin: '*'
            allowCredentials: true
  get-orders-count:
    handler: src/get-orders-count_handler.handler
    events:
      - http:
          path: /get-orders-count
          method: get
          cors:
            origin: '*'
            allowCredentials: true
  get-order:
    handler: src/get-order_handler.handler
    events:
      - http:
          path: /get-order
          method: post
          cors:
            origin: '*'
            allowCredentials: true
  search-orders:
    handler: src/search-orders_handler.handler
    events:
      - http:
          path: /search-orders
          method: post
          cors:
            origin: '*'
            allowCredentials: true

plugins:
  - serverless-offline-ssm
  - serverless-offline
  - serverless-plugin-monorepo

custom:
  serverless-offline:
    port: 3001
